### ISSUE TITLE
2d image to 3d rig parameter transformation problem

### ISSUE THREAD

**Issue by ruisizhang123** [bindita/ExprGen#2]
Hi, I am implementing the paper "Learning to Generate 3D Stylized Character Expressions from Humans". In 4.2.1 Section(Human to Character Transfer), you mentioned that **"The pairs of a human input image and the 3D parameters corresponding to the 2D character image with similar expression "**. 

But I found the character expression name in 3d database is different from the name in 2d database. I wonder if there is a mapping information between 2d character name and 3d character name?

**Comment by bindita** [comment]
yes, the 2D image dataset has more images than the number of 3D expressions. We used a rendering code written in mayapy to render the 3D expressions into 2D to get the corresponding images. We will add that code to this project by the end of this week.

**Comment by ruisizhang123** [comment]
Thanks for that!

**Comment by ruisizhang123** [comment]
Hi, about the image generation code, is it ready at present? Thanks again for your great work!

**Comment by bindita** [comment]
Hello, extremely sorry for delaying this for so long. It is ok if you don't need it anymore, but I have uploaded the code for it under the name renderfrommaya.py.
